name: samvaad
region: nyc
services:
  - name: api
    github:
      repo: atharva-again/samvaad
      branch: deploy/digital-ocean
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: PORT
        value: "8000"
      - key: ENVIRONMENT
        value: "production"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GEMINI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GROQ_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: VOYAGE_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DEEPGRAM_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DAILY_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: LLAMA_CLOUD_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
